### PR TITLE
ENH: Adds new transformer for AMRFinderPlusAnnotationsDirFmt to qiime2.Metadata

### LINKED ISSUE #5: ENH: Transformer from AMRFinderPlusAnnotationsDirFmt to immutable.Metadata.
To use GenomeData[AMRFinderPlusAnnotations]  with metadata tabulate function, a transformer is needed from AMRFinderPlusAnnotationsDirFmt to immutable.Metadata.

### PR DESCRIPTION
**Pull request by VinzentRisch**
closes #5
depends on #7 

- Adds new transformer from AMRFinderPlusAnnotationsDirFmt to qiime2.Metadata.
- Now all output files by amrfinderplus actions can be used with `metadata tabulate`

### Set up an environment 
```
mamba create -y -n q2-amrfinderplus -c https://packages.qiime2.org/qiime2/2024.10/metagenome/staged/ -c conda-forge -c bioconda --strict-channel-priority qiime2 q2-types q2-feature-table q2cli q2-metadata ncbi-amrfinderplus
```

### Run it locally 

1. First, clone the repo and checkout the PR branch:
```bash
git clone https://github.com/bokulich-lab/q2-amrfinderplus.git
cd q2-amrfinderplus
git fetch origin pull/6/head:pr-6
git checkout pr-6
pip install -e .
```

2. Download test files 
[PR-102.zip](https://github.com/user-attachments/files/16392106/PR-102.zip)

3. Test it out!
```bash
qiime metadata tabulate --m-input-file amr_all_mutations_contigs.qza --o-visualization amr_all_mutations_contigs.qzv
qiime metadata tabulate --m-input-file amr_all_mutations_feature.qza --o-visualization amr_all_mutations_feature.qzv
qiime metadata tabulate --m-input-file amr_all_mutations_sample_mags.qza --o-visualization amr_all_mutations_sample_mags.qzv
qiime metadata tabulate --m-input-file amr_annotations_contigs.qza --o-visualization amr_annotations_contigs.qzv
qiime metadata tabulate --m-input-file amr_annotations_feature.qza --o-visualization amr_annotations_feature.qzv
qiime metadata tabulate --m-input-file amr_annotations_sample_mags.qza --o-visualization amr_annotations_sample_mags.qzv
```

4. open them with 
```bash
qiime tools view amr_annotations_sample_mags.qzv

```

### CODE REVIEW

**Review by misialq — COMMENTED** [review]
Hey @VinzentRisch, this has all the changes from your other PR as well, right? Can you please rebase it on top of that other branch so that we only see the changes relevant to this PR here? Thanks! 🙏

**Comment by VinzentRisch** [comment]
Hmm I do not understand how that works.
I rebased it onto the commit [ee66471](https://github.com/bokulich-lab/q2-amrfinderplus/pull/6/commits/ee66471cc4bee2e37c681a3c687b6e96debab885) becuase thats the last one that the both branches share. I thought that was the way to go but that does not work.
should I rebase it on the newest commit on the other branch?

**Comment by misialq** [comment]
Ah, sorry, my comment was incorrect - you should rebase on top of main as we want to see the diff between this branch here and the main branch, without taking into account the other changes. If you think, though, that this branch and the one you started it from are too entangled, it may not work - in this case it will be easier to first merge the other PR and then rebase this one on top of main. Which do you think is easier?

**Comment by VinzentRisch** [comment]
Yeah lets merge the other one first. I cant get it to work with the rebase.

**Comment by VinzentRisch** [comment]
Hi @misialq 
I tried to use the genome_dict that I created also here but realized that that doesnt work because in the `AMRFinderPlusAnnotationsDirFmt` there are suffixes in the filenames so the ids are not correct anymore.
Should i just create a separate genome_dict for `AMRFinderPlusAnnotationsDirFmt` or leave it like this?

**Comment by misialq** [comment]
Hey @VinzentRisch, could you please include some example of what the `genome_dict` returns now and what you want to get? I'm not sure I quite see what you mean 😞

**Comment by VinzentRisch** [comment]
Im sorry 
So Amrfinderplusannotationdirfmt does not have a genome_dict function i just wanted to ask if you think it makes sense to add one that i can use it here for the transformer 
But I mean for now maybe its okay without because I am not using the format as an input anywhere else. 
Could you have a look at this today? then Liz can add the plugin to the distro tomorrow hopefully

**Comment by VinzentRisch** [comment]
No I'm gonna do the genome_dict anyway for the `Amrfinderplusannotationdirfmt` so I can use it here for the transformer.

**Review by misialq — APPROVED** [review]
LGTM! 🚀

**Pull request merged**
